routes/web.php
<?php

use Bittacora\OrderStatus\Http\Controllers\OrderStatusController;

Route::prefix('bpanel')->middleware(['web', 'auth','admin-menu'])->name('order-status.')->group(function(){
    Route::get('order-status', [OrderStatusController::class, 'index'])->name('index');
    Route::get('order-status/create/language/{locale?}', [OrderStatusController::class, 'create'])->name('create');
    Route::post('order-status/store', [OrderStatusController::class, 'store'])->name('store');
    Route::get('order-status/{model}/edit/language/{locale?}', [OrderStatusController::class, 'edit'])->name('edit');
    Route::put('order-status/{model}/update/language/{locale?}', [OrderStatusController::class, 'update'])->name('update');
    Route::delete('order-status/{model}', [OrderStatusController::class, 'destroy'])->name('destroy');
});

resources/views/create.blade.php
@extends('bpanel/layouts.bpanel-app')

@section('title', 'Crear estado de pedido')

@section('content')
    <p class="alert alert-success">
        <i class="fas fa-info-circle"></i> {!!  __('order-status::order-status.create_default_language') !!}
    </p>
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0 d-flex justify-content-between">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('order-status::order-status.add') }}</span>
            </h4>
            <img src="{{asset('assets_bpanel/flags/'.$language.'.png')}}" alt="{{ $language }}">
        </div>

        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('order-status.store')}}" enctype="multipart/form-data">
            @csrf
            @livewire('form.input-text', ['name' => 'name', 'labelText' => __('order-status::order-status.name'), 'required'=>true])
            @livewire('utils::tinymce-editor', ['name' => 'annotation', 'labelText' => __('order-status::order-status.annotation')])
            @livewire('form.input-checkbox', ['name' => 'active', 'value' => 1, 'checked' => true, 'labelText' => __('order-status::order-status.active'), 'bpanelForm' => true])
            @livewire('form.input-checkbox', ['name' => 'default', 'value' => 1, 'checked' => false, 'labelText' => __('order-status::order-status.default'), 'bpanelForm' => true])
            @livewire('form.input-color', ['name' => 'color', 'labelText' => __('order-status::order-status.text-color'), 'fieldWidth' => 1])
            @livewire('form.input-color', ['name' => 'background_color', 'labelText' => __('order-status::order-status.background-color'), 'fieldWidth' => 1])
            <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
                @livewire('form.save-button',['theme'=>'save'])
                @livewire('form.save-button',['theme'=>'reset'])
            </div>
            @livewire('form.input-hidden', ['name' => 'locale', 'value'=> $language])
        </form>
    </div>
@endsection

resources/views/edit.blade.php
@extends('bpanel/layouts.bpanel-app')

@section('title', 'Editar estado de pedido')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0 d-flex justify-content-between">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('order-status::order-status.edit') }}</span>
            </h4>
            <img src="{{asset('assets_bpanel/flags/'.$language.'.png')}}" alt="{{ $language }}">
        </div>

        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('order-status.update', ['model' => $model, 'locale' => $language])}}" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            @livewire('form.input-text', ['name' => 'name', 'labelText' => __('order-status::order-status.name'), 'required'=>true, 'value' => $model->name])
            @livewire('utils::tinymce-editor', ['name' => 'annotation', 'labelText' => __('order-status::order-status.annotation'), 'value' => $model->annotation])
            @livewire('form.input-checkbox', ['name' => 'active', 'value' => 1, 'checked' => $model->active == 1, 'labelText' => __('order-status::order-status.active'), 'bpanelForm' => true])
            @livewire('form.input-checkbox', ['name' => 'default', 'value' => 1, 'checked' => $model->default == 1, 'labelText' => __('order-status::order-status.default'), 'bpanelForm' => true])
            @livewire('form.input-color', ['name' => 'color', 'labelText' => __('order-status::order-status.text-color'), 'fieldWidth' => 1, 'value' => $model->color])
            @livewire('form.input-color', ['name' => 'background_color', 'labelText' => __('order-status::order-status.background-color'), 'fieldWidth' => 1, 'value' => $model->background_color])
            <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
                @livewire('form.save-button',['theme'=>'save'])
                @livewire('form.save-button',['theme'=>'reset'])
            </div>
            @livewire('form.input-hidden', ['name' => 'id', 'value'=> $model->id])
            @livewire('form.input-hidden', ['name' => 'locale', 'value'=> $language])
        </form>
    </div>
@endsection

resources/views/index.blade.php
@extends('bpanel/layouts.bpanel-app')

@section('title', 'Estados de pedido')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('order-status::order-status.order-status_list') }}</span>
            </h4>
        </div>
        <div class="card-body">
            @livewire('order-status::order-status-datatable', [], key('orderstatusdatatable'))
        </div>

    </div>
@endsection

@push('scripts')
    <script src="https://cdn.jsdelivr.net/npm/livewire-sortablejs@0.x.x/dist/livewire-sortable.min.js" defer></script>
@endpush

resources/views/livewire/order-status-datatable.blade.php
<td>
    <span class="d-inline-block" style="color:{{$row->color}};background-color:{{$row->background_color}};padding:7.5px 15px;border-radius:10px;">
        {{ $row->name }}
    </span>
</td>
<td>
    @livewire('language::datatable-languages', ['model' => $row, 'createRouteName' => 'order-status.create', 'editRouteName' => 'order-status.edit'], key('languages-order-status-'.$row->id))
</td>
<td>
    @livewire('utils::datatable-default', ['fieldName' => 'active', 'model' => $row, 'value' => $row->active, 'size' => 'xxs'], key('active-order-status-'.$row->id))
</td>
<td>
    <div class="d-flex justify-content-center align-items-center">
            <span class="align-items-center badge bgc-purple-d1 pos-rel text-white radius-4 px-3">
                <span class="bgc-primary-tp4 opacity-5 position-tl h-100 w-100 radius-4"></span>
                <span class="pos-rel">
                    {{$row->order_column}}
                </span>
            </span>
    </div>
</td>
<td>
    @livewire('utils::datatable-action-buttons', ['actions' => ['edit', 'delete'], 'scope' => 'order-status', 'model' => $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'el estado de pedido?'], key('order-status-buttons-'.$row->id))
</td>